### ISSUE TITLE
mouse click drag functionality

### ISSUE THREAD

**Issue by zainkarsan7** [printablealice/draw_robots#4]
Not really an issue, but noticed I don't get mouse click functionality with BEGIN_BUFFER, I have to use CAMERA_2D instead. Wonder why

**Comment by printablealice** [comment]
Hey! Would you be able to maybe post the code you're running? Would love to help, but not sure I fully understand (not sure what BEGIN_BUFFER refers too, or which mouse click functionality you have in mind) -Jim

**Comment by zainkarsan7** [comment]
`void my_app() {

    //make a list of points along a circle
    
    vec2 *positions = (vec2 *)calloc(NUM_BALLS, sizeof(vec2));
    vec3 *colors = (vec3*)calloc(NUM_BALLS, sizeof(vec3));
    
    for (int i = 0; i < NUM_BALLS; i++) {
        double x = cos(i*6.28 / NUM_BALLS);
        double y = sin(i*6.28 / NUM_BALLS);
        positions[i] = { x,y };
        colors[i] = { RAND(0,1),RAND(0,1),RAND(0,1) };
    }
    while (!KEY_PRESSED['Q']) {
        //BEGIN_FRAME(PV, 2.5, 'F', BLACK);
        POLL_INPUT();
        CAMERA_2D(PV, 2.5);
        CLEAR_DRAW_BUFFER(BLACK);

        DRAW_(2, POINTS, NUM_BALLS, positions, colors);
        
        DRAG_2D_POINTS_(PV, NUM_BALLS, positions, YELLOW);
        END_FRAME();
    }


}`

thats my attempt to draw draggable points arrayed in a circle, CAMERA_2D lets me drag points, BEGIN BUFFER doesnt

**Comment by printablealice** [comment]
`
  void my_app() {
  
      //make a list of points along a circle
  
      int NUM_BALLS = 10;
      vec2 *positions = (vec2 *)calloc(NUM_BALLS, sizeof(vec2));
      vec3 *colors = (vec3*)calloc(NUM_BALLS, sizeof(vec3));
  
      for (int i = 0; i < NUM_BALLS; i++) {
          double x = cos(i*6.28 / NUM_BALLS);
          double y = sin(i*6.28 / NUM_BALLS);
          positions[i] = { x,y };
          colors[i] = { RAND(0,1),RAND(0,1),RAND(0,1) };
      }
      while (!KEY_PRESSED['Q']) {
          BEGIN_FRAME(PV, 2.5, 'F', BLACK);
          // POLL_INPUT();
          // CAMERA_2D(PV, 2.5);
          // CLEAR_DRAW_BUFFER(BLACK);
  
          DRAW_(2, POINTS, NUM_BALLS, positions, colors);
  
          DRAG_2D_POINTS_(PV, NUM_BALLS, positions, YELLOW);
          END_FRAME();
      }
  }
`

I can drag the points with the above points; unable to reproduce.

**Comment by zainkarsan7** [comment]
oh k i commented out poll input and clear draw buffer and now can drag stuff. I've been pulling things from hello triangle without knowhing what they doing

**Comment by printablealice** [comment]
I could have been more clear in hello triangle

```
        BEGIN_FRAME(PV, 2.5, 'F', BLACK);
```

expands to

```
        POLL_INPUT();             // grab mouse and keyboard input and store in globals
        CAMERA_2D(PV, 2.5); // macro for a basic interactive 2D camera
        // note: creates PV = PerspectiveMatrix * ViewMatrix using initial screen height 2.5
        FULLSCREEN_TOGGLE('F');   // press this key to toggle fullscreen
        CLEAR_DRAW_BUFFER(BLACK); // clear the draw buffer to black
```

**Comment by printablealice** [comment]
Though if you're curious *why* you got the behavior you did, it's probably a result of polling input twice :)

**Comment by zainkarsan7** [comment]
yes i see that now also by peeking definition in vis studio.  thanks
